In [4]:
import os
import sys
import math
import numpy as np
import fcntl
import multiprocessing as mp
import time

# GULLS
Gulls is a mission simulation code written by Mathew Peeny for the purpose of determining exoplanet occurance rates from the Roman mission. Its function and results are throuroughly described in the following papers: [Penny at al. (2019)](https://iopscience.iop.org/article/10.3847/1538-4365/aafb69/pdf) and [Penny et al. (2013)](https://arxiv.org/pdf/1206.5296). For the purposed of this notebook, we will be concentrating mostly on the details regarding use of this code. Gulls is freely available on [GitHub](https://github.com/gulls-microlensing/gulls). The dev version is [here](https://github.com/gulls-microlensing/gulls/tree/dev). I believe to pull this branch you'll need to do the following git commands:
```bash
git fetch origin dev
git merge dev
```

There are up to date [observatory files](https://lsu.box.com/s/ypk9lnvfjt9vn7zs68bdql9fwf0mn0ex) here for now and a good fraction of the  [synthpop catalogs](https://lsu.box.com/v/gulls-surot2d-H2023) can be found here (these are very large)





## Modularity
Gulls is designed to be highly modular. The simulation code runs by loading text files of planet, lens, and source samples. It applies filter, candence, telescope optics and camera metrics, and reduction approximations using information provided in a parameter file. The outputs are text files for event parameters and weights, lightcurves, and Ficher matrix approximations of SL lightcurve fit posteriors. We can easily replace the source and lens sample files for ones created with a different galactic model, extinction map, or different pointings. We can swap our planetary catalouges to one weighted by a different planetary mass function. We can swap of filters, observation location, cadence or camera array by providing a different option in the parameter file. The same skeleton gulls codes can be used to simulated events and determine occurance rates, with a variety of different mission designs.

+ [] add starlists under galactic model
+ [] add field image next to geometry
+ [] replace first LC image with a set of "science" images
+ [] replace the html with a static image


<div style="display: flex; justify-content: center; align-items: center;">
    <div style="margin-right: 0px;">
        <div style="font-size: 40px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px; margin-left: -120px;">
            planet model
        </div>
        <div style="font-size: 20px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 40px; margin-left: -120px;">
            (e.g. the Casan et al., 2010 mass function)
        </div>
        <img src="./Assets/planetMF.jpg" alt="planetary mass function" height="325">
        <div style="font-size: 50px; line-height: 0.5; margin-top: 20px; margin-bottom: 30px; text-align: center; margin-left: -120px;">
            &#x2193;
        </div>
    </div>
    <div style="margin-left: -220px;">
        <div style="font-size: 40px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px;">
            galactic model
        </div>
        <div style="font-size: 20px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 50px;">
            (e.g. synthpop; velocity, density, mass, magnitude)
        </div>
        <img src="./Assets/Milky_Way.jpg" alt="milky way model" height="300">
        <div style="display: flex; justify-content: space-between; margin-top: 20px;">
            <div style="font-size: 50px; line-height: 0.5; margin-bottom: 10px; margin-left: 80px;">
                &#x2193;
            </div>
            <div style="font-size: 50px; line-height: 0.5; margin-bottom: 10px; margin-right: -100px;">
                &#x2193;
            </div>
        </div>
    </div>
</div>

<div style="display: flex; justify-content: center; align-items: center;">
    <div style="text-align: center; margin-right: 0px;">
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 45px;">
            companion objects
        </div>
        <img src="./Assets/planetlist.png" alt="planet list" height="200"> 
        <div style="font-size: 50px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            &#x2193;
        </div>
    </div>
    <div style="text-align: center; margin-left: -40px;">
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            lens objects
        </div>
        <div style="font-size: 20px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            (no magnitude limit)
        </div>
        <img src="./Assets/lenslist.png" alt="lens list" height="200">
        <div style="font-size: 50px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            &#x2193;
        </div>
    </div>
    <div style="text-align: center; margin-left: -20px;">
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            source stars
        </div>
        <div style="font-size: 20px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            (e.g. H<25 limited)
        </div>
        <img src="./Assets/starlist.png" alt="source list" height="200">
        <div style="font-size: 50px; line-height: 0.5; margin-top: 20px; margin-bottom: 10px;">
            &#x2193;
        </div>
    </div>
</div>

<div style="display: flex; justify-content: center; align-items: center;">
    <div style="margin-right: 0px;">
        <div style="font-size: 40px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px; margin-left: -120px;">
            planet injection
        </div>
        <div style="font-size: 20px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 2px; margin-left: -120px;">
            (<i>s, q, u<sub>0</sub></i>)
        </div>
        <img src="./Assets/planet.png" alt="another figure" height="325"> 
    </div>
    <div style="margin-left: -200px;">
        <div style="font-size: 40px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px;">
            event geometry
        </div>
        <div style="font-size: 20px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px;">
            (D<sub>S</sub>>D<sub>L</sub>)
        </div>
        <img src="./Assets/event_geometry.png" alt="event geometry" height="300">
    </div>
</div>

<div style="text-align: center;">
    <!-- Unicode down arrow with increased font size and margin -->
    <div style="font-size: 100px; line-height: 0.5; margin-bottom: 50px; margin-top: 20px;">
        &#x2193;
    </div>
    <div>
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 40px;">
            generate science images
        </div>
        <img src="./Assets/apjsaafb69f11_hr.jpg" alt="penny2019 figure" width="500">
    </div>
    <div style="font-size: 100px; line-height: 0.5; margin-bottom: 50px; margin-top: 20px;">
        &#x2193;
    </div>
    <div>
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 40px;">
            extract lightcurves
        </div>
        <img src="./Assets/apjsaafb69f11_hr.jpg" alt="penny2019 figure" width="500">
    </div>
    <div>
        <div style="font-size: 40px; line-height: 0.5; margin-top: 20px; margin-bottom: 40px;">
            fit a single lens lightcurve
        </div>
        <div style="font-size: 20px; line-height: 0.5; text-align: center; margin-top: 20px; margin-bottom: 10px;">
            (&#916;&#967;<sup>2</sup> = &#967;<sup>2</sup><sub>actual</sub> - &#967;<sup>2</sup><sub>single</sub>)
        </div>
    </div>
    <div style="display: flex; justify-content: center; align-items: center; margin-top: 20px;">
        <!-- Green circle with tick and text -->
        <div style="text-align: center; margin-right: 20px;">
            <div style="font-size: 24px; margin-bottom: 10px;">&#916;&#967;<sup>2</sup> &gt; 160</div>
            <svg width="100" height="100" viewBox="0 0 50 50">
                <circle cx="25" cy="25" r="25" fill="green" />
                <text x="25" y="25" dy="0.35em" font-size="30" text-anchor="middle" fill="white">&#x2714;</text>
            </svg>
        </div>
        <!-- Red circle with cross and text -->
        <div style="text-align: center;">
            <div style="font-size: 24px; margin-bottom: 10px;">&#916;&#967;<sup>2</sup> &lt; 160</div>
            <svg width="100" height="100" viewBox="0 0 50 50">
                <circle cx="25" cy="25" r="25" fill="red" />
                <text x="25" y="25" dy="0.35em" font-size="30" text-anchor="middle" fill="white">&#x2716;</text>
            </svg>
        </div>
    </div>
</div>

<div style="text-align: center; margin-top: 50px; margin-bottom: 50px;">
    <img  src="./Assets/occurance_rates.png" alt="penny2019 figure" width="500">
</div>


## Language
Gulls is primarily built in pearl and c++. The scripts to create the required input catalogues are pearl. Pearl is a fast maguage and this speed allows us to create large catologues very fast. The bones of the gulls simulations procedures are build in c++. The simulation and fitting of each event is independent of the other events in the catalogue. This makes these simulations embarassingly parallelisable. c and c++ are typical laguage choices for parallelisable jobs. c++ reequires an objects size in memory to be specified at initilisation; there is no appending a list. This is usufull in parallelised code because it avoids memory overlaps or time spent reorganiseing an objects location in memory as it grows. This priciple is the same as why numpy arrays are so much faster than python for loops. The array is size defined at intilisation and operations on these array run on c backends. It is also how cython achieves for loop speed up; the cython additions require you to inilisae your python objects with a defined type and size, similar to c and c++. The analysis process for a simulation run is usually a baspoke process. There are some python scripts to aid in the analysis process, where ease of use is a more pressing concern than than speed. 

## Monte Carlo Inference
Gulls determines occurance rates through monte carlo inference. Its draws from samples of lens, and source objects create using a galactic model. These samples, weighted by their effective area, become the galactic model prior in the inference. Each lens source combination has an optical depth and event rate which are used to weight the events samples acording to there probability of lensing. For example, if the source is closer to the observer than the lens there is 0 probaility of a lensing event. These weights are defined as follows:

equation

The planet samples can be drawn from any distribution, but some distributions make for more efficient inference than others. If, for example, we draw from uniform planet distributions (the samples in our planet catalgue would have mass and semi-majoraxis histograms that are flat). However, these mass and semi-major axis will be tranformed into s and q in the planet injection step and s and q are not uniformly efficient at creating detectable planet singnals in light curves. Microlensing is most efficient at detecting s and q of 1. So a uniform planet prior will result in excessive sampling in the s=1, q=1 parameter space, and a relative undersampling in high s and low q (i.e. low mass, high semimajor axis); the parameter space of greatest interest for eoplanet studies. The benefit of monte carlo intergration is that we can keep collecting samples untill the whole parameter space is well sampled, but it would be more efficient to draw more often from those parameters than are less likely to show detection, so that the posterior is similarly well sampled in low probabily regions. In order to maintain our probability in the inference process, we weight the planet samples so as to transform the distribution from which we draw samples into the distribution we expect the planets to have. In our uniform examples, we might weight each mass draw according to its relative probabilty in a planetary mass function, such as the Cassan mass function. An event, with a planetary, lens and source sample, is acepted into the posterior sample if the planet is "detected" (the criteria from this is discussed in the following section). Each posterior sample then has weights to transform the sample into the representive posterior. There is a planetary weight, which transform the planetary prior to match an expected distribution, and an event weight, which transforms the lens and source priors to incorporate the probability of a lensing event occuring. 

## Lightcurve Analysis

## installation

## Post Processing

## Toybox Example

The length of a planet file (nl) dictates the length of a gulls subrun. The subruns (nf) are independent and can be increased incrementally to reduce the uncertainty in the infered yeild estimates.

In [5]:
# Append the Modules directory to sys.path
sys.path.append("../Modules")
from Simulations import Planet

In [6]:
# Creating planet files
start_time = time.time()
planet = Planet(live_run=True, nl=5)
planet.draw_planet_sample()
print('state:', planet.state[:,:5,:])
end_time = time.time()
print(f"Execution time: {end_time - start_time:.2f} seconds")

Initializing Planet class...
cell: 0: [[7.98066359e-06 2.00086761e+00 8.85086635e+01 6.79127718e+01]
 [7.82919893e-06 1.02048114e+01 6.35129924e+01 2.04173106e+02]
 [7.73100856e-06 2.79815663e+00 5.70832746e+01 2.92142087e+01]
 [2.35664333e-05 1.20977355e+00 4.67075316e+01 2.37539151e+02]
 [2.30299945e-05 5.00514207e+00 7.26199602e+01 6.75066516e-01]]
worker: planet_state: 1: [[ 3.99031397e-06  6.95898050e-01 -3.64665624e+01  2.93601568e+02]
 [ 2.45139821e-04  5.11417361e-01 -4.92707758e+01  8.79817005e+01]
 [ 3.64574589e-07  2.97961099e+01  6.20870701e+01  9.66663443e+01]
 [ 1.73378116e-05  1.05334147e+01 -3.30095245e+01  4.37237340e+01]
 [ 9.70056155e-05  3.82908307e-01  3.22300329e+01  2.32084289e+02]]
worker: planet_state: 0: [[ 9.18332457e-05  1.58276442e+00  3.71097560e+01  1.29746400e+02]
 [ 6.76428561e-06  3.36280542e+00 -2.56258515e+01  1.57836911e+01]
 [ 4.02839857e-06  9.11263687e-01  7.37318899e+01  3.35993207e+02]
 [ 5.07888714e-07  2.89900104e+00  3.39790841e+01  5.521075

/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simulations.py:140: RuntimeWarning: invalid value encountered in arccos
  np.arccos(2.0 * rnd),
/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simulations.py:141: RuntimeWarning: invalid value encountered in arccos
  -np.arccos(2.0 - 2.0 * rnd)
/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simulations.py:140: RuntimeWarning: invalid value encountered in arccos
  np.arccos(2.0 * rnd),
/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simulations.py:141: RuntimeWarning: invalid value encountered in arccos
  -np.arccos(2.0 - 2.0 * rnd)
/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simulations.py:140: RuntimeWarning: invalid value encountered in arccos
  np.arccos(2.0 * rnd),
/Users/malpas.1/Code/eLearning/TheMicrolensersGuideToTheGalaxy/Notebooks/../Modules/Simu

In [ ]:
import sys
import multiprocessing as mp
import planet_file

def worker(rundes, nl, nf, file_ext):
    planet_file.generate_planets(rundes, nl, nf, file_ext)

    if len(sys.argv) < 4:
        print(f"Usage: python {sys.argv[0]} nl nf file_ext")
        sys.exit(1)

    rundes = sys.argv[0].split('/')[-1].split('.')[0]
    nl = 
    nf = 
    file_ext = 

    processes = []
    for _ in range(mp.cpu_count()):
        p = mp.Process(target=worker, args=(rundes, nl, nf, file_ext))
        processes.append(p)
        p.start()

    for p in processes:
        p.join()

In [17]:
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import json

class Field:
    def __init__(self, x_size, y_size, pointing, model_base_name=None, filters=['default_filter'], 
                 psf_model='default_psf', model_name="besancon_Robin2003", 
                 extinction_map={"extinction_map_kwargs": {"name": "Marshall"}, 
                                 "extinction_law_kwargs": {"name": "ODonnellCardelli"}
                                 }, 
                solid_angle=5.0e-3, name_for_output=None):
        self.x_size = x_size
        self.y_size = y_size
        self.l, self.b = pointing
        self.filters = filters
        self.psf_model = psf_model
        self.galactic_model = model_name
        self.extinction_map = extinction_map
        self.solid_angle = solid_angle
        if model_base_name is None:
            self.model_base_name = f"{self.l}-{self.b}-{self.solid_angle}-{self.galactic_model}"
        date = datetime.now().strftime("%Y%m%d")  # Format the date as YYYYMMDD
        if name_for_output is None:
            self.name_for_output = self.key+date
        self.name_for_output = name_for_output

    def create_json_file(self):
        data = {
            "model_base_name": self.model_base_name,
            "name_for_output": self.name_for_output,
            "l_set": [self.l],
            "b_set": [self.b],
            "solid_angle": self.solid_angle,
            "model_name": self.galactic_model,
            "evolution_class": {
                "name": "MIST",
                "interpolator": "CharonInterpolator"
            },
            "extinction_map_kwargs": self.extinction_map["extinction_map_kwargs"],
            "extinction_law_kwargs": self.extinction_map["extinction_law_kwargs"],
            "delta_t_minutes": [192, 15],
            "microlensing_event_parameters": {
                "mag_bin_edges": [20, 21, 22, 23, 24, 25, 26],
                "events_u0_per_mag_bin": [[200, 0.1], [200, 0.01], [200, 0.001]],
                "t_E_mins": 200,
                "t0_mins": 2160
            }
        }

        with open('synthpop_config.json', 'w') as json_file:
            json.dump(data, json_file, indent=4)

    def draw_lens_sample(self):
        # Placeholder for draw_lens_sample method
        pass

    def draw_source_samples(self):
        # Placeholder for draw_source_samples method 
        pass

    def generate_field(self):
        # Placeholder for generate_field method
        pass



class Event:
    def __init__(self, field, planet):
        self.field = field
        self.planet = planet

    def generate_microlensing_events(self, n):
        self.field.create_json_file(n)
        self.field.draw_lens_sample(n)
        self.field.draw_source_samples(n)
        self.field.generate_field(n)  # n?
        self.planet.draw_planet_sample(n)

    def prior(self):
        # Placeholder for prior method
        self.generate_microlensing_events(self.nwalker)


    def generate_science_images(self):
        # Placeholder for generate_science_images method
        pass

    def extract_lightcurve(self):
        # Placeholder for extract_lightcurve method
        pass

    def binary_magnification(self):
        # Placeholder for binary_magnification method
        pass
